version: '2'
services:
  mongodb:
    image: mongo
    container_name: mongo-database
    ports:
      - "27017:27017"
    volumes:
      - "custom_value:/data/db"
      # replace with your volume
  app:
    container_name: mutant-app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
